package spongecell.guardian.rules.core
 
import spongecell.guardian.model.HDFSDirectory 
import spongecell.guardian.notification.GuardianEvent 
import spongecell.guardian.notification.SlackGuardianWebHook  

/*
 * This rule checks that the number of files in a directory.
 */
dialect "mvel"

rule "1 HDFS Heston Status Check"
    when
        $hdfsDir : HDFSDirectory(statusCheck == HDFSDirectory.FILE_CHECK_UNKNOWN) 
    then
        System.out.println("HDFSDirectory Status Check - statusCheck: " + 
        	$hdfsDir.statusCheck);
end

dialect "mvel"
rule "Slack Notifier"
    when
        $slackClient : SlackGuardianWebHook(sendMsg == false && messageSent == false)
        $slackEvent : GuardianEvent()
        $slackHdfsDir : HDFSDirectory() 
    then
      	modify ($slackClient) {
        	setSendMsg(Boolean.FALSE),	
        	setMessageSent(Boolean.TRUE),	
      	}
 		$slackEvent.setSource(drools.getRule().getName());	
        $slackEvent.setManagedObject($slackHdfsDir.getTargetDir()),
        $slackEvent.setEventSeverity("INFORMATIONAL"),	
        $slackEvent.setBody($slackHdfsDir.getRawFileStatus()),
       	$slackEvent.setValid(Boolean.FALSE)	
       	
        System.out.println("Sending notifications:");
	    $slackClient.send($slackEvent.getJsonEventMessage(), SlackGuardianWebHook.EMOJI_WORKFLOW_ONE);
end